# config/database.yml
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  # Disable foreign key constraints for multitenancy
  variables:
    foreign_keys: "OFF"

development:
  primary:
    <<: *default
    database: storage/development.sqlite3
  # Template database for creating new tenant databases
  tenant_template:
    <<: *default
    database: storage/tenant_template.sqlite3

test:
  primary:
    <<: *default
    database: storage/test.sqlite3
  tenant_template:
    <<: *default
    database: storage/test_tenant_template.sqlite3

production:
  primary:
    <<: *default
    database: storage/production.sqlite3
  cache:
    <<: *default
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate
  tenant_template:
    <<: *default
    database: storage/production_tenant_template.sqlite3